apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdocker
  template:
    metadata:
      labels:
        app: testdocker
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: app
        image: douglascezaro/app:latest
        ports:
        - containerPort: 80
          name: testdocker